version: "3.0"

services:
  piccont:
    image: suco3693/cloudstaypicimg:version2
    depends_on:
      - 'cloudstaypicdb'
    ports:
      - '80:3006'
  pic-seed:
    image: suco3693/cloudstaypicimg:version2
    depends_on:
      - 'cloudstaypicdb'
    command: sh -c 'npm run seed'
  cloudstaypicdb:
    image: mongo:latest
